/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#474649",
        "primary": "#adc6ff",
        "inverse-surface": "#e5e2e3",
        "on-primary-fixed": "#001a42",
        "secondary-container": "#474649",
        "tertiary-fixed-dim": "#ffb786",
        "tertiary": "#ffb786",
        "on-primary-container": "#00285d",
        "primary-container": "#4d8eff",
        "secondary-fixed-dim": "#c8c6c8",
        "background": "#131314",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2b",
        "on-tertiary-fixed": "#311400",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffdcc6",
        "on-surface": "#e5e2e3",
        "secondary-fixed": "#e4e2e4",
        "surface-bright": "#3a393a",
        "primary-fixed": "#d8e2ff",
        "outline": "#8c909f",
        "outline-variant": "#424754",
        "surface-container-low": "#1c1b1c",
        "secondary": "#c8c6c8",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-container": "#b6b4b7",
        "surface": "#131314",
        "error": "#ffb4ab",
        "surface-container": "#201f20",
        "on-primary-fixed-variant": "#004395",
        "on-surface-variant": "#c2c6d6",
        "inverse-primary": "#005ac2",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#002e6a",
        "tertiary-container": "#df7412",
        "on-tertiary-container": "#461f00",
        "on-secondary": "#303032",
        "on-background": "#e5e2e3",
        "surface-dim": "#131314",
        "surface-container-highest": "#353436",
        "surface-container-lowest": "#0e0e0f",
        "error-container": "#93000a",
        "surface-variant": "#353436",
        "on-secondary-fixed": "#1b1b1d",
        "surface-tint": "#adc6ff",
        "on-tertiary": "#502400",
        "inverse-on-surface": "#313031"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "soria": ["Soria", "Newsreader", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1.5rem", "full": "9999px"
      },
    },
  },
  plugins: [],
}
